# This is a basic workflow to help you get started with Actions

name: Shutdown GitHub-Test-VM

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: "SharedServicesKeyVault"
        secrets: 'TenantID, SubscriptionID, TerraformSpSecret, TerraformSPID, TerraformStorageKey, github-test-admin-user, github-test-admin-pass'
      id: GetSecretAction
    
    - name: Azure CLI Action
      uses: Azure/cli@1.0.4
      with:
      # Specify the script here
        inlineScript: az vm stop --resource-group GitHub-Test-RG --name GitHub-Test-VM
