name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release
      
      
    - name: Azure Container Registry Login
    uses: Azure/docker-login@v1
    with:
      # Container registry username
      username: # default is 
      # Container registry password
      password: # default is 
      # Container registry server url
      login-server: # default is https://index.docker.io/v1/
