name: eShopOnWeb Build and Push

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Azure Container Registry Login
    uses: Azure/docker-login@v1
    with:
      username: hippokrates
      password: ${{ secrets.registrypass }}
      login-server: hippokrates.azurecr.io
      
      
    - name: Build and push Docker images
    uses: docker/build-push-action@v2.4.0
    with:
      # List of extra privileged entitlement (eg. network.host,security.insecure)
      allow: # optional
      # List of build-time variables
      build-args: # optional
      # Builder instance
      builder: # optional
      # List of external cache sources for buildx (eg. user/app:cache, type=local,src=path/to/dir)
      cache-from: # optional
      # List of cache export destinations for buildx (eg. user/app:cache, type=local,dest=path/to/dir)
      cache-to: # optional
      # Build's context is the set of files located in the specified PATH or URL
      context: # optional
      # Path to the Dockerfile
      file: src/Web/Dockerfile
      # List of metadata for an image
      labels: # optional
      # Load is a shorthand for --output=type=docker
      load: # optional, default is false
      # Set the networking mode for the RUN instructions during build
      network: # optional
      # Do not use cache when building the image
      no-cache: # optional, default is false
      # List of output destinations (format: type=local,dest=path)
      outputs: # optional
      # List of target platforms for build
      platforms: # optional
      # Always attempt to pull a newer version of the image
      pull: # optional, default is false
      # Push is a shorthand for --output=type=registry
      push: 
      # List of secrets to expose to the build (eg. key=string, GIT_AUTH_TOKEN=mytoken)
      secrets: # optional
      # List of secret files to expose to the build (eg. key=filename, MY_SECRET=./secret.txt)
      secret-files: # optional
      # List of SSH agent socket or keys to expose to the build
      ssh: # optional
      # List of tags
      tags: hippokrates.azurecr.io/eshop:latest
      # Sets the target stage to build
      target: # optional
      # GitHub Token used to authenticate against a repository for Git context
      github-token: # optional, default is ${{ github.token }}
      

